Updated and removed some outdated configuration **CHINESE ONLY**
LeavesMC/Documentation pull request #22
Opened 2024-08-02 12:49 UTC by WhitePhosphor

As the title says.

2024-08-02 12:56 UTC, WhitePhosphor commented
English document needed.

If no one can do this I'll use machine translation then.

2024-08-02 13:03 UTC, WhitePhosphor commented
#21

2024-08-02 13:14 UTC, MC-XiaoHei commented
未完成，使用draft

2024-08-02 13:29 UTC, LittleChest commented
？可以直接转

2024-08-03 03:24 UTC, LittleChest requested changes
新的审阅请查收w

2024-08-03 03:24 UTC, LittleChest commented on src/config-spec/leaves/zh_Hans.yml
> +        description: '是否允许假人使用 [动作](fakeplayer#%E5%81%87%E4%BA%BA%E5%8A%A8%E4%BD%9C)。'
没有出现中英文混合的情况 不需要加空格

2024-08-03 03:24 UTC, LittleChest commented on src/config-spec/leaves/zh_Hans.yml
> +        description: '是否允许带有乘客（身上有骑着实体）的生物进行世界间传送。'
通过传送门传送

2024-08-03 03:24 UTC, LittleChest commented on src/config-spec/leaves/zh_Hans.yml
> +      description: '是否在靴子拥有 [摔落缓冲](https://zh.minecraft.wiki/w/%E6%91%94%E8%90%BD%E7%BC%93%E5%86%B2) 魔咒时不会导致耕地被踩坏为泥土。'
同上

2024-08-03 03:24 UTC, LittleChest commented on src/config-spec/leaves/zh_Hans.yml
> +      description: '是否允许在主副手无物品时，按下使用键能够直接打开有告示牌挂在其前方的箱子。'
可能需要译名标准化（？）

2024-08-03 03:24 UTC, LittleChest commented on src/config-spec/leaves/zh_Hans.yml
> +        是否禁用铁砧“过于昂贵！”的限制。
它叫铁砧惩罚

2024-08-03 03:24 UTC, LittleChest commented on src/config-spec/leaves/zh_Hans.yml
> +      description: '是否启用 [漏斗计数器](https://github.com/gnembon/quick-carpet/blob/master/README.md#hoppercounters) 与对应的命令 `/leaves counter`。'
同上

2024-08-03 03:24 UTC, LittleChest commented on src/config-spec/leaves/zh_Hans.yml
> +      description: '是否允许守卫者在被闪电束击中后变化为远古守卫者。'
~~在~~ 变化 -> 转化

2024-08-03 03:24 UTC, LittleChest commented on src/config-spec/leaves/zh_Hans.yml
> +        description: '是否开启 [Servux](https://modrinth.com/mod/servux) 的结构探测支持。如果是，那么服务端将会向客户端发送结构信息。'
我认为不需要有更多的解释 前面一句话已经清晰的说明了它的用途

2024-08-03 03:24 UTC, LittleChest commented on src/config-spec/leaves/zh_Hans.yml
> +        description: '是否开启 [Servux](https://modrinth.com/mod/servux) 的生物探测支持。如果是，那么服务端将会向客户端发送生物相关信息。'
同上

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/getting-started.md
> +确保你的文件资源管理器已经进入到 Leaves 所在的文件夹，并将你下载的文件名修改为 `leaves.jar`。
这其实是指 cd 到对应目录（

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/getting-started.md
> +`--nogui` 用于禁用服务端的 GUI。因此在使用该命令行运行服务端时，不会同时出现 cmd 以及 GUI 这两个界面。
感觉此行不需要变动

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/migration.md
> +在开始之前，我们建议你先对服务端进行完整备份。
此行不需要变动

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/migration.md
> +任何试图同时支持模组和插件的混合服务端都存在严重问题，在这我们不建议使用它们。
~~在这~~

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/migration.md
> +别担心！如果你没有动过关键的文件，即使发生了这种情况，你也不会丢失任何原来的数据。
此行不需要变动 我们假设用户完全遵循文档

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/migration.md
> +原版服务端只是不知道该去哪里寻找这两个世界的文件。这个时候，我们需要进行手动更改。
多余的描述 此行不需要变动

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/migration.md
> +如果不采取这些步骤，下界和末地将会被重置。
确实是“看起来” 此行不需要变动

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/migration.md
> +下面是一张展示了原版和 Leaves 存储世界的一一对应关系的图表。
世界存储对应关系的图表
或
世界存储的区别的图表

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/migration.md
> +如果你的 `level-name` 并不是 `world` ，请在以下所有步骤中将“ `world` ”替换为你设置的 `level-name` ！
中文句点与英文之间不需要空格
看起来不需要引号 代码块很明显吧

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/next-steps.md
> +在安装任何插件之前，请你确保插件来源可以被信任。
此行可能不需要更改

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/next-steps.md
> +因此，请从受信任的来源安装插件。务必小心！
添加“仅”

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/next-steps.md
> +**插件不仅可以访问你的服务器，还可以不受限制地访问运行着服务端的物理机的存储系统。**
此行可能不需要更改
这样更看不懂了ww

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/next-steps.md
> +### 安装插件
白名单不需要插件 在这里添加安装插件不合适

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/next-steps.md
> +权限（Permission）是一种控制玩家在服务器上能做什么和不能做什么的方法。
为什么要加英文呢

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/next-steps.md
> +Leaves 提供了许多协议支持，这些协议用于与客户端上的模组通讯以增强游玩体验。
游玩 -> 游戏

但是感觉没什么必要 Leaves本来就是游戏服务器（

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/next-steps.md
> +如果出现一些重大问题，你可以使用备份将服务器恢复到未出现问题的状态。
此行不需要变动
~~这也是我写的~~

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/next-steps.md
> +最常见的做法之一就是为服务器运行正确的启动参数。
运行 -> 添加

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/next-steps.md
> +你可以使用 [PaperMC 的启动脚本生成器](https://docs.papermc.io/misc/tools/start-script-gen) 为服务器生成带有优化后的参数的启动脚本。
中文之间不需要空格

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/next-steps.md
> +除此以外，[本指南](https://paper-chan.moe/paper-optimization/) 还将帮助你进一步优化服务器。
同上

2024-08-03 03:24 UTC, LittleChest commented on src/zh_Hans/leaves/guides/next-steps.md
> +如果想将服务器公开，那么你需要转发服务器端口。这样，局域网外的人就可以连接到你的服务器。
此行不需要更改

2024-08-03 12:34 UTC, WhitePhosphor reviewed
25%

2024-08-03 12:34 UTC, WhitePhosphor commented on src/config-spec/leaves/zh_Hans.yml
> +      description: '是否允许在主副手无物品时，按下使用键能够直接打开有告示牌挂在其前方的箱子。'
这里我实在不知道怎么改了😇

2024-08-03 12:42 UTC, LittleChest commented
完成后点一下`解决对话`谢谢（

2024-08-03 12:45 UTC, WhitePhosphor reviewed
Done

~我再也不想看我自己拉的史了~

2024-08-03 12:45 UTC, WhitePhosphor commented on src/zh_Hans/leaves/guides/getting-started.md
> +`--nogui` 用于禁用服务端的 GUI。因此在使用该命令行运行服务端时，不会同时出现 cmd 以及 GUI 这两个界面。
确实 感觉我写的有点拗口 但是当时为了赶时间就没仔细想这里（

2024-08-03 12:45 UTC, WhitePhosphor commented on src/zh_Hans/leaves/guides/migration.md
> +任何试图同时支持模组和插件的混合服务端都存在严重问题，在这我们不建议使用它们。
我不在😭

2024-08-03 12:45 UTC, WhitePhosphor commented on src/zh_Hans/leaves/guides/next-steps.md
> +### 安装插件
这里可能是原来想在这边插入一段写插件的

但是不知道为什么忘掉了www

2024-08-03 12:45 UTC, WhitePhosphor commented on src/zh_Hans/leaves/guides/next-steps.md
> +权限（Permission）是一种控制玩家在服务器上能做什么和不能做什么的方法。
~P4特有的脑回路不正常~

2024-08-03 12:45 UTC, WhitePhosphor commented on src/zh_Hans/leaves/guides/next-steps.md
> +如果出现一些重大问题，你可以使用备份将服务器恢复到未出现问题的状态。
~小箱子也干了~

2024-08-03 12:51 UTC, LittleChest commented on src/config-spec/leaves/zh_Hans.yml
> +      description: '是否允许在主副手无物品时，按下使用键能够直接打开有告示牌挂在其前方的箱子。'
是否允许在主副手均无物品时按下使用键直接打开支撑告示牌的箱子。

2024-08-03 12:58 UTC, LittleChest approved these changes

2024-08-03 12:59 UTC, WhitePhosphor commented
所以缺失的英文这一块

谁来补（

2024-08-03 13:10 UTC, LittleChest commented
> 所以缺失的英文这一块
> 
> 谁来补（

放心 上一个commit的英文还没写

2024-08-03 14:27 UTC, merged